default: &default
  adapter: postgresql
  encoding: unicode
  pool: <%= ENV.fetch("RAILS_MAX_THREADS") { 5 } %>
  username: vimeotemp
  password: <%= ENV['VIMEOTEMP_DATABASE_PASSWORD'] %>

development:
  <<: *default
  host: localhost
  database: vimeotemp_dev

test:
  <<: *default
  host: localhost
  database: vimeotemp_test

production:
  <<: *default
  database: vimeotemp_production
